idf_component_register(
    SRCS
        "main.c"
        "app.c"
    INCLUDE_DIRS "."
    REQUIRES
        system_info
        board
        button_charge_request
        hal_uart
        modbus
        pzem
        inverter
        esp_timer
        charge_request_iface
        charge_abort_iface
        wifi
        web
)
